package es.iessaladillo.juegos.saladillo.model.components;

/**
 * Enumeración que contiene todos los posibles tipos que adoptará un elemento del fondo.
 *
 */
public enum TipoFondo { 
	CAMINOARENA,
	CAMINOARENACOMBINADOU,
	CAMINOARENACOMBINADOD,
	CAMINOARENACOMBINADOL,
	CAMINOARENACOMBINADOR,
	CAMINOARENACURVALU,
	CAMINOARENACURVALD,
	CAMINOARENACURVARU,
	CAMINOARENACURVARD,
	CAMINOARENAHORIZONTAL,
	CAMINOARENAVERTICAL,
	CARRETERA,
	CESPED,
	CESPEDCOMBINADOU,
	CESPEDCOMBINADOD,
	CESPEDCOMBINADOL,
	CESPEDCOMBINADOR,
	CESPEDCURVALD,
	CESPEDCURVALU,
	CESPEDCURVARD,
	CESPEDCURVARU,
	CESPEDHORIZONTAL,
	CESPEDSENDERO,
	CESPEDSENDEROCURVALD,
	CESPEDSENDEROCURVALU,
	CESPEDSENDEROCURVARD,
	CESPEDSENDEROCURVARU,
	CESPEDSENDEROHORIZONTAL,
	CESPEDSENDEROVERTICAL,
	CESPEDVERTICAL,
	CAMINOARENACESPEDCURVALD,
	CAMINOARENACESPEDCURVALU,
	CAMINOARENACESPEDCURVARD,
	CAMINOARENACESPEDCURVARU,
	CAMINOARENAGRAVILLALD,
	CAMINOARENAGRAVILLALU,
	CAMINOARENAGRAVILLARD,
	CAMINOARENAGRAVILLARU;
}
