/**
 * 
 */
package clases;

/**
 * @author Annais
 *
 */
public enum TipoFondo { CAMINOARENA, CAMINOARENACOMBINADOD, CAMINOARENACOMBINADOL, CAMINOARENACOMBINADOR, CAMINOARENACOMBINADOU,
	CAMINOARENACURVALD, CAMINOARENACURVALU, CAMINOARENACURVARU,
	CAMINOARENACURVARD, CAMINOARENAHORIZONTAL, CAMINOARENAVERTICAL, CARRETERA, CESPED,
	CESPEDCOMBINADOD, CESPEDCOMBINADOL, CESPEDCOMBINADOR, CESPEDCOMBINADOU,
	CESPEDCURVALD, CESPEDCURVALU, CESPEDCURVARD, CESPEDCURVARU, CESPEDHORIZONTAL,
	CESPEDSENDERO, CESPEDSENDEROCURVALD, CESPEDSENDEROCURVALU, CESPEDSENDEROCURVARD,
	CESPEDSENDEROCURVARU, CESPEDSENDEROHORIZONTAL, CESPEDSENDEROVERTICAL, CESPEDVERTICAL,
	CAMINOARENACESPEDCURVALD, CAMINOARENACESPEDCURVALU, CAMINOARENACESPEDCURVARD,
	CAMINOARENACESPEDCURVARU, CAMINOARENAGRAVILLALD, CAMINOARENAGRAVILLALU,
	CAMINOARENAGRAVILLARD, CAMINOARENAGRAVILLARU;
}
